-- Drop the PETRESCUE table in case it exists
drop table PETRESCUE;
-- Create the PETRESCUE table 
create table PETRESCUE (
	ID INTEGER NOT NULL,
	ANIMAL VARCHAR(20),
	QUANTITY INTEGER,
	COST DECIMAL(6,2),
	RESCUEDATE DATE,
	PRIMARY KEY (ID)
	);
-- Insert sample data into PETRESCUE table
insert into PETRESCUE values 
	(1,'Cat',9,450.09,'2018-05-29'),
	(2,'Dog',3,666.66,'2018-06-01'),
	(3,'Dog',1,100.00,'2018-06-04'),
	(4,'Parrot',2,50.00,'2018-06-04'),
	(5,'Dog',1,75.75,'2018-06-10'),
	(6,'Hamster',6,60.60,'2018-06-11'),
	(7,'Cat',1,44.44,'2018-06-11'),
	(8,'Goldfish',24,48.48,'2018-06-14'),
	(9,'Dog',2,222.22,'2018-06-15')
	
;

SELECT SUM(COST) FROM PETRESCUE;
SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;
SELECT MAX(QUANTITY) FROM PETRESCUE;
SELECT AVG(QUANTITY) FROM PETRESCUE;
SELECT AVG(COST) FROM PETRESCUE;


SELECT ANIMAL, ROUND(COST) FROM PETRESCUE;
SELECT ANIMAL, LENGTH(ANIMAL) FROM PETRESCUE;
SELECT ANIMAL, UPPER(ANIMAL) FROM PETRESCUE;
SELECT DISTINCT(UPPER(ANIMAL)) FROM PETRESCUE;
SELECT *, LOWER(ANIMAL) FROM PETRESCUE WHERE ANIMAL = 'Cat';

SELECT *, DAY(RESCUEDATE) AS DAY, MONTH(RESCUEDATE) AS MONTH FROM PETRESCUE WHERE ANIMAL= 'Cat';
SELECT *, MONTH(RESCUEDATE) AS MONTH FROM PETRESCUE WHERE MONTH(RESCUEDATE) = 5;
SELECT *, DAY(RESCUEDATE) AS DAY FROM PETRESCUE WHERE DAY(RESCUEDATE) = 14;
SELECT *, (RESCUEDATE + 3) AS VET_DAY FROM PETRESCUE;
SELECT *, (CURRENT_DATE - RESCUEDATE) AS DIFF FROM PETRESCUE;